med_id/med_id/Controllers/PendidikanController.cs
using med_id.datamodels;
using med_id.Services;
using med_id.viewmodels;
using Microsoft.AspNetCore.Mvc;

namespace med_id.Controllers
{
    public class PendidikanController : Controller
    {
        PendidikanService pendidikanService;
        public PendidikanController(PendidikanService _pendidikanService)
        {
            pendidikanService = _pendidikanService;
        }

        public async Task<IActionResult>Index1(string sortOrder, string searchString)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
           
            ViewBag.CurrentFilter = searchString;
            List<MEducationLevel> data = await pendidikanService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }

            return View(data);
        }
        public IActionResult Create()
        {
            MEducationLevel data = new MEducationLevel();
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(MEducationLevel dataParam)
        {
            dataParam.CreatedBy = 1;
            VMResponse respon = await pendidikanService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<JsonResult> CheckNameIsExsist(string name, int id)
        {
            bool isExist = await pendidikanService.CheckName(name, id);
            return Json(isExist);
        }

        public async Task<IActionResult> Edit(int id)
        {
            MEducationLevel data = await pendidikanService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MEducationLevel dataParam)
        {
            dataParam.ModifiedBy = 1;
            VMResponse respon = await pendidikanService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            MEducationLevel data = await pendidikanService.GetDataById(id);
            return PartialView(data);
        }

        /*      [HttpGet("HapusData")]*/
        public async Task<IActionResult> Delete(int id)
        {
            MEducationLevel data = await pendidikanService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            int modifedby = 1;
            VMResponse respon = await pendidikanService.Delete(id, modifedby);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }
    }
}

med_id/med_id/Views/Pendidikan/Create.cshtml
@using med_id.datamodels;
@model MEducationLevel


<div class="card">
    <div class="card-body">
        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-2 row mt-4">
                <label for="Name" class="col-sm-4 col-form-label">Nama*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Name" Name="Name" oninput="check_valid()" value="@Model.Name">
                <span id="tesName" class="text-danger"></span>
            </div>
            <div class="mb-4 row col-12">
                <div class="col-6"></div>
                <div class="col-2">
                    <a class="btn btn-light" asp-controller="Pendidikan" asp-action="Index1">Batal</a>
               
                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </div>
            </div>

        </form>
    </div>

</div>

<script>
    function check_valid() {
        $("#tesName").text("")

    }



    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
            }
        },
        messages: {
            Name: {
                required: "Nama Harus Diisi, Tidak Boleh Kosong",
            }
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var name= $("#Name").val()
            var id= 0

            $.ajax({
                url: "/Pendidikan/CheckNameIsExsist",
                type: "get", //type atau method sama aja.
                data: { name: name, id: id },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#tesName").text("Nama Sudah Ada")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })
    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Pendidikan/Create",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")
                    Swal.fire({
                        icon: "success",
                        title: "Data Berhasil Ditambah",
                        showConfirmButton: false,
                        timer: 1500
                    }).then(function () {
                        window.location.reload()
                    })
                    
                }
                else {
                    alert("Gagal Menyimpan")
                }

            }
        })
    }

</script>

med_id/med_id/Views/Pendidikan/Delete.cshtml
@using med_id.datamodels;
@model MEducationLevel
<div class="card">
    <div class="card-body d-flex">


        <form asp-action="SureDelete" method="post" id="form_delete">


            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id" />

            <div class="mb-4 mt-4 card-body">Anda akan menghapus jenjang pendidikan <b>@Model.Name ?</b></div>
            
            <div class="row col-12">
                <div class="col-7"></div>
                <div class="col-3">
                    <a class="btn btn-outline-primary" asp-controller="Pendidikan" asp-action="Index1">Tidak</a>

                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">
                        Ya
                    </button>
                </div>
            </div>
           @*  <div >
                <a class="btn btn-outline-primary" asp-controller="Pendidikan" asp-action="Index1">Tidak</a>
                <button type="submit" class="btn btn-primary">Ya</button>
            </div> *@

        </form>

    </div>
</div>

<script>

    $("#form_delete").validate
        ({
            submitHandler: function (form) {

                var id = $("#Id").val()

                $.ajax
                    ({
                        url: '/Pendidikan/SureDelete',
                        type: "post",
                        data: { id: id },
                        dataType: "json",
                        success: function (respon) {
                            var data = respon.dataRespon

                            if (data.success) {

                                $("#my_modal").modal("hide")
                                Swal.fire({
                                    icon: "success",
                                    title: "Data Berhasil Dihapus",
                                    showConfirmButton: false,
                                    timer: 1500
                                }).then(function () {
                                    window.location.reload()
                                })
                            }
                            else {
                                alert("Gagal Menghapus")
                            }

                        }
                    })

            }

        })

</script>

med_id/med_id/Views/Pendidikan/Edit.cshtml
@using med_id.datamodels;
@model MEducationLevel

<div class="card">
    <div class="card-body">
        <form asp-action="Edit" method="post" id="form_input">

            <input type="hidden" class="form-control" id="Id" Name="Id" value="@Model.Id">
            <div class="mb-2 row mt-4">
                <label for="Name" class="col-sm-4 col-form-label">Nama*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input type="text" class="form-control" id="Name" Name="Name" oninput="check_valid()" value="@Model.Name">
            </div>
                <span id="validate_Name" class="text-danger"></span>
            <div class="mb-4 row col-12">
                <div class="col-6"></div>
                <div class="col-2">
                    <a class="btn btn-light" asp-controller="Pendidikan" asp-action="Index1">Batal</a>

                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">
                        Simpan
                    </button>
                </div>
            </div>

        </form>
    </div>

</div>
@* <div class="card">
    <div class="card-body">
        <form asp-action="Edit" method="post" id="form_input">

            <input type="hidden" class="form-control" id="Id" Name="Id" value="@Model.Id">

            <div class="mb-4 row ">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" Name="Name" value="@Model.Name">
                    <span id="validate_Name" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                    <a class="btn btn-light" asp-controller="Pendidikan" asp-action="Index">
                        Bact to List
                    </a>
                </div>
            </div>
        </form>

    </div>
</div> *@

<script>
    function check_valid() {
        $("#validate_Name").text("")

    }
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
            }
        },
        messages: {
            Name: {
                required: "Please fill Name",
            }
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var name= $("#Name").val()
            var id = $("#Id").val();

            $.ajax({
                url: "/Pendidikan/CheckNameIsExsist",  
                type: "get",
                data: { name: name, id: id}, 
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_Name").text("Name Already Axists")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })
    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Pendidikan/Edit",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")
                    Swal.fire({
                        icon: "success",
                        title: "Data Berhasil Diubah",
                        showConfirmButton: false,
                        timer: 1500
                    }).then(function () {
                        window.location.reload()
                    })
                }
                else {
                    alert("Gagal Mengubah")
                }

            }
        })
    }

</script>

med_id/med_id/Views/Pendidikan/Index1.cshtml
@using med_id.datamodels;
@using med_id.viewmodels;
@model List<MEducationLevel>
<div class="card">
    <div class="card-body">

        <div class="row mb-3">
            <div class="col-12">
                <div class="mt-4 mb-4">

                    <h3 style="color:darkblue" class="align-center">
                        Jenjang Pendidikan
                    </h3>

                </div>
                <div class="d-flex justify-content-between ">
                    <button id="btn_create" class="btn btn-primary mt-10">Tambah</button>
                    <form asp-action="Index1">
                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search by Nama" />
                            <div class="input-group-prepend">
                                <button type="submit" class="input-group-text" title="search">
                                    <i class="bi bi-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        <table class="table table-hover mb-3">
            <thead>
                <tr class="table-info">
                    <th class="col-9">
                        <a asp-action="Index1" asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-currentFilter="@ViewBag.currentFilter">
                            Nama
                        </a>
                    </th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>
                                <a style="color:white" class="btn btn-primary btn_edit" dataid="@item.Id">
                                    Ubah
                                </a>
                                <a style="color:white" class="btn btn-danger btn_delete" dataid="@item.Id">
                                    Hapus
                                </a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>Data not found</td>
                    </tr>
                }


            </tbody>

        </table>
    </div>
@* 
    <div class="card-footer">
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <div class="row">
            <div class="col-1 m">
                <form asp-action="Index1" id="form_pagesize">
                    <select name="PageSize" id="PageSize" class="form-control">
                        <option value="3">3</option>
                        <option value="5">5</option>
                        <option value="10">10</option>
                    </select>
                </form>
            </div>
            <div class="col-5"></div>
            <div class="col-4">
                Page @Model.PageIndex of @Model.TotalPages
                <a asp-action="Index1"
                   asp-route-sortOrder="@ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFilter"
                   asp-route-pageSize="@ViewBag.CurrentPageSize"
                   class="btn btn-info float-right @prevDisabled">
                    Previous
                </a>
                <a asp-action="Index1"
                   asp-route-sortOrder="@ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFilter"
                   asp-route-pageSize="@ViewBag.CurrentPageSize"
                   class="btn btn-info float-right @nextDisabled">
                    Next
                </a>
            </div>
        </div>


    </div> *@
</div>
<script>
    $("#btn_create").click(function () {
        $("#modal-body").empty()
        $("#modal-body").load("/Pendidikan/Create")
        $("#my_modal").modal("show")
        $("#modal_judul").text("Tambah").css("color", "blue")
    })
    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")
        $("#modal-body").empty()
        $("#modal-body").load("/Pendidikan/Delete?id=" + id)
        $("#my_modal").modal("show")
        $("#modal_judul").text("Hapus!").css("color", "red")
    })
    $(".btn_edit").click(function () {
        var id = $(this).attr("dataid")
        $("#modal-body").empty()
        $("#modal-body").load("/Pendidikan/Edit?id=" + id)
        $("#my_modal").modal("show")
        $("#modal_judul").text("Edit").css("color", "blue")
    })

    $("#PageSize").val(@ViewBag.CurrentPageSize)

    $("#PageSize").change(function () {
        $("#form_pagesize").submit()
    })
</script>