med_id/med_id/Controllers/DoctorController.cs
using med_id.datamodels;
using med_id.Services;
using med_id.viewmodels;
using Microsoft.AspNetCore.Mvc;

namespace med_id.Controllers
{
    public class DoctorController : Controller
    {
        private DoctorService doctorService;
        private SpesialisasiDokterService spesialisasiDokterService;


        private readonly IWebHostEnvironment webHostEnvirontment;
        public DoctorController(DoctorService _dokterService, IWebHostEnvironment _webHostEnvirontment, SpesialisasiDokterService _spesialisasiDokterService)
        {
            doctorService = _dokterService;
            webHostEnvirontment = _webHostEnvirontment;
            spesialisasiDokterService = _spesialisasiDokterService;
        }
        public async Task<IActionResult> IndexDetail(int id)
        {
            VMDoctorProfile data = await doctorService.GetDataByIdProfile(id);
            return View(data);
        }
        public async Task<IActionResult> Index(int id)
        {
            VMDoctorProfile data = await doctorService.GetDataByIdProfile(id);
            return View(data);
        }
        public string Upload(IFormFile ImageFile)
        {
            string uniqueFileName = "";

            if (ImageFile != null)
            {
                string uploadFolder = Path.Combine(webHostEnvirontment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    ImageFile.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        [HttpPost]
        public async Task<IActionResult> SaveImg(VMSavePoto dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.ImagePath = Upload(dataParam.ImageFile);
            }
            //dataParam.CreateBy = IdUser;
            VMResponse respon = await doctorService.SaveImg(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Create(int id)
        {
            VMDoctorProfile data = await doctorService.GetDataByIdProfile(id);

            List<MSpecialization> listCategory = await spesialisasiDokterService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMDoctorProfile dataParam)
        {
            dataParam.CreatedBy = 1;
            VMResponse respon = await doctorService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMDoctorProfile data = await doctorService.GetDataByIdProfile(id);

            List<MSpecialization> listCategory = await spesialisasiDokterService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMDoctorProfile dataParam)
        {
            dataParam.CreatedBy = 1;
            VMResponse respon = await doctorService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<JsonResult> CheckTokenIsExist(int id, string nameDay, int nameJam, int nameMenit)
        {
            string day = nameDay;
            if (day == "1")
            {
                day = "Senin";
            }
            if (day == "2")
            {
                day = "Selasa";
            }
            if (day == "3")
            {
                day = "Rabu";
            }
            if (day == "4")
            {
                day = "Kamis";
            }
            if (day == "5")
            {
                day = "Jumat";
            }
            if (day == "6")
            {
                day = "Sabtu";
            }
            if (day == "0")
            {
                day = "Minggu";
            }
            bool isExist = await doctorService.CheckJadwal(id, day, nameJam, nameMenit);
            return Json(isExist);
        }

    }
}

med_id/med_id/Controllers/PatientController.cs
using med_id.datamodels;
using med_id.Services;
using med_id.viewmodels;
using Microsoft.AspNetCore.Mvc;

namespace med_id.Controllers
{
    public class PatientController : Controller
    {
        private PatientService patientService;

        public PatientController(PatientService _patientService)
        {
            patientService = _patientService;
        }
        public IActionResult Index()
        {
            return View();
        }

        //view ini mereturn data kumpulan dokter
        public async Task<IActionResult> FindDoctor()
        {
            List<VMFindDoctor> data = await patientService.GetAllData();
            return View(data);
        }

        public async Task<JsonResult> GetDataDays(int id, int medicalFacilityId)
        {
            List<VMSchedule> dataSchedule = await patientService.GetDataDaysById(id, medicalFacilityId);
            return Json(dataSchedule);
        }

        public async Task<IActionResult> MakeAppointment(int id, int idPatient, int medicalFacilityId)
        {
            VMFindDoctor data = await patientService.GetDataById(id);

            //butuh data family member 
            List<VMFamilyMember> dataFamily = await patientService.GetDataByIdParent(idPatient);
            ViewBag.listDataFamily = dataFamily;
            //butuh data medical facility
            VMFindDoctor dataMedFacility = await patientService.GetDataMedicalFacility(id);
            ViewBag.dataMedFacility = dataMedFacility;

            //butuh data medical treatment
            VMTreatment dataTreatment = await patientService.GetDataTreatmentById(id);
            ViewBag.treatment = dataTreatment;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAppointment(VMFindDoctor dataParam)
        {
            List<VMFullSlotDate> responseSlot = await patientService.GetFullSlotDate(dataParam.DoctorId);
            //cek tanggal di dataParam dgn tanggal responseSlot, kalo ada brrti false bisa simpan data
            //Console.WriteLine(dataParam.AppointmentDate.Date);
            
            for(int i = 0; i < responseSlot.Count(); i++)
            {
            //Console.WriteLine(responseSlot[i].AppointmentDate.Value.Date);
                if(dataParam.AppointmentDate.Date == responseSlot[i].AppointmentDate.Value.Date)
                {
                    VMResponse response = new VMResponse();
                    response.Success = false;
                    response.Message = "Slot sudah penuh";

                    return Json(response);
                }
            }
            //kalau penuh, mau nampilin modal load slot penuh 

            VMResponse responseAppointment = await patientService.MakeAppointment(dataParam);

            if (responseAppointment.Success)
            {
                return Json(responseAppointment);
            }

            return View(dataParam);
        }

        public async Task<IActionResult> DoctorProfile(int id)
        {
            VMFindDoctor data = await patientService.GetDataById(id);

            VMFindDoctor dataMedFacility = await patientService.GetDataMedicalFacility(id);
            ViewBag.dataMedFacility = dataMedFacility;

            return View(data);
        }

        public async Task<IActionResult> MakeAppointmentById(int id, int idPatient, int medicalFacilityId)
        {
            VMFindDoctor data = await patientService.GetDataById(id);

            //butuh data family member 
            List<VMFamilyMember> dataFamily = await patientService.GetDataByIdParent(idPatient);
            ViewBag.listDataFamily = dataFamily;
            //butuh data medical facility
            VMFindDoctor dataMedFacility = await patientService.GetDataMedicalFacility(id);
            ViewBag.dataMedFacility = dataMedFacility;

            //butuh data tanggal kedatangan (m_medical_facility_schedule)
            //List<VMSchedule> dataSchedule = await patientService.GetDataDaysById(id, medicalFacilityId);
            //ViewBag.schedule = dataSchedule;

            //butuh data medical treatment
            VMTreatment dataTreatment = await patientService.GetDataTreatmentById(id);
            ViewBag.treatment = dataTreatment;

            ViewBag.medicalFacilityId = medicalFacilityId;

            return PartialView(data);
        }

        public async Task<IActionResult> EditAppointment(int id, int idPatient, int appointmentId)
        {
            //data dokter
            VMFindDoctor data = await patientService.GetDataById(id);

            //butuh data family member 
            List<VMFamilyMember> dataFamily = await patientService.GetDataByIdParent(idPatient);
            ViewBag.listDataFamily = dataFamily;

            //butuh data medical facility
            VMFindDoctor dataMedFacility = await patientService.GetDataMedicalFacility(id);
            ViewBag.dataMedFacility = dataMedFacility;

            ////butuh data tanggal kedatangan (m_medical_facility_schedule)
            //List<VMSchedule> dataSchedule = await patientService.GetDataDaysById(id, medicalFacilityId);
            //ViewBag.schedule = dataSchedule;

            //butuh data medical treatment
            VMTreatment dataTreatment = await patientService.GetDataTreatmentById(id);
            ViewBag.treatment = dataTreatment;

            ViewBag.appointmentId = appointmentId;

            VMAppointments dataAppointment = await patientService.GetAppointmentById(appointmentId);
            ViewBag.dataAppointment = dataAppointment;

            return PartialView(data);
        }

        public async Task<JsonResult> GetFullSlotDate(int id)
        {
            List<VMFullSlotDate> data = await patientService.GetFullSlotDate(id);
            return Json(data);
        }

        public async Task<IActionResult> FullSlot()
        {
            return PartialView();
        }

        public async Task<IActionResult> Appointments()
        {
            int IdBiodata = HttpContext.Session.GetInt32("IdBiodata") ?? 5;
            List<VMAppointments> data = await patientService.GetAppointments(IdBiodata);
            return View(data);
        }

        [HttpPut]
        public async Task<IActionResult> EditAppointment(int idAppointment, VMFindDoctor dataParam)
        {
            List<VMFullSlotDate> responseSlot = await patientService.GetFullSlotDate(dataParam.DoctorId);
            //cek tanggal di dataParam dgn tanggal responseSlot, kalo ada brrti false bisa simpan data
            //Console.WriteLine(dataParam.AppointmentDate.Date);

            for (int i = 0; i < responseSlot.Count(); i++)
            {
                //Console.WriteLine(responseSlot[i].AppointmentDate.Value.Date);
                if (dataParam.AppointmentDate.Date == responseSlot[i].AppointmentDate.Value.Date)
                {
                    VMResponse response = new VMResponse();
                    response.Success = false;
                    response.Message = "Slot sudah penuh";

                    return Json(response);
                }
            }
            //kalau penuh, mau nampilin modal load slot penuh 

            VMResponse responseAppointment = await patientService.EditAppointment(idAppointment, dataParam);

            if (responseAppointment.Success)
            {
                return Json(responseAppointment);
            }

            return View(dataParam);
        }
    }
}

med_id/med_id/Views/Patient/Appointments.cshtml
@using med_id.viewmodels

@{
    int idBiodata = @Context.Session.GetInt32("IdBiodata") ?? 5;
}

<h1>Rencana Kedatangan</h1>

<div class="row">
    @foreach (VMAppointments item in Model)
    {
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@item.Fullname</h5>
                    <div class="row">
                        <div class="col-9">
                            <p><b>Faskes</b> @item.MedicalFacility</p>
                            <p><b>Tanggal</b> @item.AppointmentDate.Value.Date.ToString("dd/MM/yyyy")</p>
                            <p><b>Waktu</b> @item.ScheduleStart - @item.ScheduleEnd</p>
                            <p><b>Tindakan</b> @item.Treatment</p>
                        </div>
                        <div class="col-3 d-flex align-items-end">
                            <a class="btn btn-primary btn_edit_appointment" data-appointment-id="@item.IdAppointment" data-doctor-id="@item.IdDoctor">Ubah Kedatangan</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    }
</div>

<script>
    $(".btn_edit_appointment").click(function () {
        var idAppointment = $(this).data("appointment-id")
        var idDoctor = $(this).data("doctor-id")

        console.log(idAppointment)

        $("#modal-body").empty()
        $("#modal-body").load("/Patient/EditAppointment?id=" + idDoctor + "&idPatient=" + @idBiodata + "&appointmentId=" + idAppointment)
        $("#my_modal").modal("show")
    })
</script>

med_id/med_id/Views/Patient/DoctorProfile.cshtml
@using med_id.viewmodels;

@{
    var medFacility = ViewBag.dataMedFacility;
    int idBiodata = @Context.Session.GetInt32("IdBiodata") ?? 0;
}

<div class="card">
    <!-- As a heading -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Home &emsp;/</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a class="navbar-brand" href="#">Cari Dokter &emsp;/</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Detail Dokter</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="card-body">
        <div class="row" style="margin-top:50px">
            <div class="col-sm-4">
                <div class="card-body text-center">
                    <img src="~/niceadmin/img/profile-img.jpg" class="rounded-circle img-thumbnail" height="220" width="220">
                </div>
            </div>

            <div class="col-sm-8">
                <div class="card-body text-left">
                    <h2>@Model.Fullname</h2>
                    <h4>&emsp; @Model.ListMedicalFacility[0].Specialization</h4>
                    <h4>&emsp; @Model.ListMedicalFacility[0].Experience Tahun Pengalaman</h4>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <div class="card-body">
                    <h4>Tindakan Medis</h4>
                    <div style="border: solid lightgrey 0.05px; border-radius:10px">
                        <h5>- Nama tindakan</h5>
                    </div>
                </div>
                <div class="card-body">
                    <h4>Riwayat Praktek</h4>
                    <div style="border: solid lightgrey 0.05px; border-radius:10px">
                        <h5>&nbsp;&nbsp;Nama RS</h5>
                        <h6> &emsp;&nbsp;&nbsp;&nbsp;Spesialisasi di faskes </h6>
                        <a style="float:right; padding-right:30px;">Tanggal mulai &nbsp  -  Sekarang</a>
                    </div>
                </div>
                <div class="card-body">
                    <h4>Pendidikan</h4>
                    <div style="border: solid lightgrey 0.05px; border-radius:10px">
                        <h5>&emsp;&nbsp;&nbsp;Nama institusi</h5>
                        <h6>&emsp; &emsp;&nbsp;&nbsp; Jurusan<a style="float:right; padding-right:30px;"> Tahun lulus</a></h6>
                    </div>
                </div>
            </div>

            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="card-body text-left">
                            <h2>@Model.Fullname</h2>
                            <h4>&emsp; @Model.ListMedicalFacility[0].Specialization</h4>
                            <h4>&emsp; @Model.ListMedicalFacility[0].Experience Tahun Pengalaman</h4>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="card-body text-center">
                            <h4>
                                <button class="btn btn-primary">Chat Dokter</button>
                            </h4>
                            <h5>Rp.30.000</h5>
                        </div>
                    </div>
                </div>
                <div class="card-body" style="">
                    <h3>Lokasi Praktek</h3>
                    @foreach (VMFindDoctor item in medFacility.ListMedicalFacility)
                    {
                        <div class="card-body mb-3" style="border: solid lightgrey 0.05px; border-radius:10px">
                            <div class="row p-2">
                                <div class="col-sm-8">
                                    <div class="card-body text-left">
                                        <h6>@item.MedicalFacilityCategoryName @item.MedicalFacilityName</h6>
                                        <h7>&emsp;Spesialisasi Faskes<a style="float:right; padding-right:30px;"></a></h7>
                                        <h7>&emsp;Lokasi<a style="float:right; padding-right:30px;"></a></h7>
                                        <h5></h5>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="card-body text-right">
                                        <h7>Konsultasi Mulai Dari</h7>
                                        <h7>Rp &nbsp;Harga mulai dari</h7>
                                    </div>

                                    <a class="btn btn-primary btn_make_appointment_profile" dataid="@item.MedicalFacilityId" data-id="@Model.DoctorId">Buat Janji</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
            
@* <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> *@

<script>
    $(".btn_make_appointment_profile").click(function () {
        var id = $(this).data("id");
        var idMedFacility = $(this).attr("dataid");

        $("#modal-body").empty();
        $("#modal-body").load("/Patient/MakeAppointmentById?id=" + id + "&idPatient=" + @idBiodata + "&medicalFacilityId=" + idMedFacility);
        $("#my_modal").modal("show");
    })
</script>

med_id/med_id/Views/Patient/FindDoctor.cshtml
@using med_id.viewmodels

@model List<VMFindDoctor>

@{
    int idRole = @Context.Session.GetInt32("IdRole") ?? 0;
    int idBiodata = @Context.Session.GetInt32("IdBiodata") ?? 0;
}

@if (idRole == 0)
{
    <h1 style="margin-top:70px">Cari Dokter</h1>

    <div class="row">
        @foreach(var item in Model)
        {
            <div class="col-6">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <div class="p-3 d-flex justify-content-center">
                                <img src="~/niceadmin/img/profile-img.jpg" class="img-fluid" style="border-radius:100px" alt="...">
                            </div>
                            <div class="p-3 d-flex justify-content-center">
                                <a href="#" class="btn" id="btn_make_appointment_login" style="background-color: darkblue; color: white">Buat Janji</a>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body h-100 d-flex align-items-center">
                                <div>
                                    <h4 class="card-title mb-0">@item.Fullname</h4>
                                    <p class="mb-0">Dokter @item.Specialization</p>
                                    <p>@item.Experience tahun pengalaman</p>
                                    <h6 class="mb-0"><i class="ri-hospital-fill"></i> @item.MedicalFacilityCategoryName @item.MedicalFacilityName</h6>
                                    <a style="width:380px;" class="btn btn-outline-primary" asp-controller="Doctor" asp-action="IndexDetail" asp-route-id="@item.DoctorId">Lihat Info Lebih Banyak</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
else if(idRole == 3)
{
    <h1 style="margin-top:70px">Cari Dokter</h1>

    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-6">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <div class="p-3 d-flex justify-content-center">
                                <img src="~/niceadmin/img/profile-img.jpg" class="img-fluid" style="border-radius:100px" alt="...">
                            </div>
                            <div class="p-3 d-flex justify-content-center">
                                <a href="#" class="btn btn_make_appointment" data-id="@item.DoctorId" style="background-color: darkblue; color: white">Buat Janji</a>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body w-100 h-100 d-flex align-items-center">
                                <div>
                                    <h4 class="card-title mb-0">@item.Fullname</h4>
                                    @if (item.ListMedicalFacility.Count() > 0)
                                    {
                                        <p class="mb-0">Dokter @item.ListMedicalFacility[0].Specialization</p>
                                        <p>@item.ListMedicalFacility[0].Experience tahun pengalaman</p>
                                    }else{
                                        <p class="mb-0">Tidak ada</p>
                                        <p>0 tahun pengalaman</p>
                                    }
                                    @foreach(VMFindDoctor item2 in item.ListMedicalFacility){
                                        <h6 class="mb-0"><i class="ri-hospital-fill"></i>@item2.MedicalFacilityCategoryName @item2.MedicalFacilityName</h6>
                                    }
                                    <a class="btn btn-primary w-100 btn_doctor_profile" asp-controller="Patient" asp-action="DoctorProfile" asp-route-id=@item.DoctorId>Lihat Profil Dokter</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <h1 class="text-center">Layanan 'Buat Janji' hanya tersedia untuk pasien.</h1>
    <h1 class="text-center">Kembali ke <a class="text-primary" href="/">Dashboard</a> atau <a class="text-primary" style="cursor:pointer" id="btn_make_appointment_login">Login sebagai pasien</a>.</h1>
}


<script>
    $("#btn_make_appointment_login").click(function () {
        
        $("#modal-body").empty()
        $("#modal-body").load("/Auth/Login")
        $("#my_modal").modal("show")
    })

    $(".btn_make_appointment").click(function () {
        var id = $(this).data("id");
        $("#modal-body").empty();
        $("#modal-body").load("/Patient/MakeAppointment?id=" + id + "&idPatient=" + @idBiodata);
        $("#my_modal").modal("show");
    })
</script>

med_id/med_id/Views/Patient/FullSlot.cshtml
<h3>Cek Ketersediaan Jadwal</h3>

<p>Mohon maaf, waktu kedatangan yang Anda pilih sudah terisi penuh. Silakan pilih waktu kedatangan atau faskes lainnya.</p>

<div>
    <a class="btn btn-primary" asp-controller="Patient" asp-action="FindDoctor">Pilih Jadwal Lain</a>
</div>