med_id/med_id/Controllers/MMedicalItemController.cs
using med_id.datamodels;
using med_id.Services;
using med_id.viewmodels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace med_id.Controllers
{
    public class MMedicalItemController : Controller
    {
        private CategoryProductKesehatanService categoryProductKesehatanService;
        private SegmentationProductKesehatanService segmentationProductKesehatanService;
        private MMedicalItemService mMedicalItemService;
        private readonly IWebHostEnvironment webHostEnvirontment;
        private int IdUser = 1;

        public MMedicalItemController(CategoryProductKesehatanService _categoryProductKesehatanService, SegmentationProductKesehatanService _segmentationProductKesehatanService, MMedicalItemService _mMedicalItemService, IWebHostEnvironment _webHostEnvirontment)
        {
            categoryProductKesehatanService = _categoryProductKesehatanService;
            segmentationProductKesehatanService = _segmentationProductKesehatanService;
            mMedicalItemService = _mMedicalItemService;
            webHostEnvirontment = _webHostEnvirontment; 
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSort = sortOrder == "price" ? "price_desc" : "price";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<VMMMedicalItem> data = await mMedicalItemService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())
                    || a.NameCategory.ToLower().Contains(searchString.ToLower())
                    || a.NameSegmentation.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                case "price_desc":
                    data = data.OrderByDescending(a => a.PriceMin).ToList();
                    break;
                case "price":
                    data = data.OrderBy(a => a.PriceMin).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }

            return View(PaginatedList<VMMMedicalItem>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMMMedicalItem data = new VMMMedicalItem();

            List<MMedicalItemCategory> listCategory = await categoryProductKesehatanService.GetAllData();
            ViewBag.ListCategory = listCategory;

            List<MMedicalItemSegmentation> listVariant = await segmentationProductKesehatanService.GetAllData();
            ViewBag.listVariant = listVariant;

            return PartialView(data);
        }

        public async Task<JsonResult> CheckNameIsExist(string name, int id, int medicalItemSegmentationId, int medicalItemCategoryId)
        {
            bool isExist = await mMedicalItemService.CheckByName(name, id, medicalItemSegmentationId, medicalItemCategoryId);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMMMedicalItem dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.ImagePath = Upload(dataParam.ImageFile);
            }
            //dataParam.CreateBy = IdUser;
            VMResponse respon = await mMedicalItemService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public string Upload(IFormFile ImageFile)
        {
            string uniqueFileName = "";

            if (ImageFile != null)
            {
                string uploadFolder = Path.Combine(webHostEnvirontment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    ImageFile.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMMMedicalItem data = await mMedicalItemService.GetDataById(id);

            List<MMedicalItemCategory> listCategory = await categoryProductKesehatanService.GetAllData();
            ViewBag.ListCategory = listCategory;

            List<MMedicalItemSegmentation> listVariant = await segmentationProductKesehatanService.GetAllData();
            ViewBag.listVariant = listVariant;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMMMedicalItem dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.ImagePath = Upload(dataParam.ImageFile);
            }
            //dataParam.CreateBy = IdUser;
            VMResponse respon = await mMedicalItemService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMMMedicalItem data = await mMedicalItemService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMMMedicalItem data = await mMedicalItemService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await mMedicalItemService.Delete(id);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }
    }
}

med_id/med_id/Views/MMedicalItem/Create.cshtml
@using med_id.viewmodels;


@model VMMMedicalItem

@{
    ViewData["Title"] = "Create Medical Item";
}

<div class="card">
    <div class="card-body">

        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>

        <form asp-action="Create" method="post" id="form_input" enctype="multipart/form-data">
            <div class="mb-4 row">
                <label for="Name" class="col-sm-4 col-form-label">Name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
                    <span id="validate_Name" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="MedicalItemCategoryId" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @if (ViewBag.ListCategory != null)
                    {
                        @Html.DropDownList("MedicalItemCategoryId",
                    new SelectList(ViewBag.ListCategory, "Id", "Name"),
                    "--Pilih Category--",
                    new {@class = "form-control"}
                    )
                    }
                    else
                    {
                        <p>Error: Data for dropdown is null.</p>
                    }
                </div>
            </div>

            <div class="mb-4 row">
                <label for="MedicalItemSegmentationId" class="col-sm-4 col-form-label">Name Segmentation</label>
                <div class="col-sm-8">
                    @if (ViewBag.ListVariant != null)
                    {
                        @Html.DropDownList("MedicalItemSegmentationId",
                    new SelectList(ViewBag.ListVariant, "Id", "Name"),
                    "--Pilih Variant--",
                    new {@class = "form-control"}
                    )
                    }
                    else
                    {
                        <p>Error: Data for dropdown is null.</p>
                    }
                </div>
            </div>

            <div class="mb-4 row">
                <label for="PriceMin" class="col-sm-4 col-form-label">Price Min</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="PriceMin" name="PriceMin" value="@Model.PriceMin">
                </div>
            </div>
            <div class="mb-4 row">
                <label for="PriceMax" class="col-sm-4 col-form-label">Price Max</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="PriceMax" name="PriceMax" value="@Model.PriceMax">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Packaging" class="col-sm-4 col-form-label">packaging</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Packaging" name="Packaging" value="@Model.Packaging">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Indication" class="col-sm-4 col-form-label">Indication</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Indication" name="Indication" value="@Model.Indication"></textarea>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Caution" class="col-sm-4 col-form-label">Jenis Obat</label>
                <div class="col-sm-8">
                    <input type="radio" name="Caution" value="bebas" checked> Obat Bebas (Tanpa Resep) <br><br>
                    <input type="radio" name="Caution" value="keras"> Obat Keras <br><br>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="ImageFile" class="col-sm-4 col-form-label">Upload Image</label>
                <div class="col-sm-8">
                    <input type="file" class="form-control" id="ImageFile" name="ImageFile" value="@Model.ImagePath">
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="MMedicalItem" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            },
            PriceMin: {
                required: true,
                number: true,
            },
            PriceMax: {
                required: true,
                number: true,
            },
            Packaging: {
                required: true,
            },
            Indication: {
                required: true,
            },
            MedicalItemCategoryId: "required",
            MedicalItemSegmentationId: "required",
            ImageFile: {
                required: true,
                typeFile: "jpg|jpeg|png",
                sizeFile: true,
            },
        },
        messages: {
            Name: {
                required: "Please fill Name",
                minlength: "The name must consist of at least 3 character"
            },
            PriceMin: {
                required: "Please fill price",
                number: "Please fill number only",
            },
            PriceMax: {
                required: "Please fill price",
                number: "Please fill number only",
            },
            Packaging: {
                required: "Please fill Packaging",
                number: "Please fill number only",
            },
            Indication: {
                required: "Please fill Packaging",
                number: "Please fill number only",
            },
            MedicalItemCategoryId: "Please select category",
            MedicalItemSegmentationId: "Please select category",
            ImageFile: {
                required: "Please fill image",
                typeFile: "Please upload jpg|jpeg|png",
                sizeFile: "Please upload file max size 1 mb",
            },
        },
        submitHandler: function (form) {
            var name = $("#Name").val()
            var id = 0
            var medicalItemSegmentationId = $("#MedicalItemSegmentationId").val()
            var medicalItemCategoryId = $("#MedicalItemCategoryId").val()

            $.ajax({
                url: "/MMedicalItem/CheckNameIsExist",
                type: "get", //type atau method sama aja.
                data: { name: name, id: id, medicalItemSegmentationId: medicalItemSegmentationId, medicalItemCategoryId: medicalItemCategoryId },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_Name").text("Name is Already Exists");
                        return true;
                    }
                    else {
                        fungsiSubmit(form)
                    }
                }

            })
        }
    })

    function fungsiSubmit(form) {
        var formData = new FormData()
        var dataForm = $(form).serializeArray()
        $.each(dataForm, function (key, input) {
            formData.append(input.name, input.value)
        })
        var file = $("#ImageFile").prop("files")
        if (file.length > 0) {
            formData.append("ImageFile", file[0])
        }
        $.ajax({
            url: "/MMedicalItem/Create",
            type: "post",
            data: formData,
            dataType: "json",
            contentType: false,
            processData: false,
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")

                    Swal.fire(
                        'information',
                        data.message,
                        'success'
                    ).then(function () {
                        window.location.reload()
                    })


                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }
    jQuery.validator.addMethod("typeFile", function (value, element, param) {
        return value.match(new RegExp("." + param + "$"));
    });
    jQuery.validator.addMethod("sizeFile", function (val, element) {
        var size = element.files[0].size;
        if (size > 1048576)
        {
            return false;
        } else {
            return true;
        }
    });


</script>

med_id/med_id/Views/MMedicalItem/Delete.cshtml
@using med_id.viewmodels;


@model VMMMedicalItem
@{
    ViewData["Title"] = "Delete Medical Item";
}

<div class="card">
    <div class="card-body">
        <form asp-action="SureDelete" method="post" id="form_delete">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <h3>Are you sure for delete @Model.Name ?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="MMedicalItem" asp-action="Index" class="btn btn-cyan">No</a>
            </div>
        </form>
    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {
            // var dataParam = $(form).serialize()
            var id = $("#Id").val()
            $.ajax({
                url: '/MMedicalItem/SureDelete',
                type: "post",
                data: { id: id },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#my_modal").modal("hide")
                        // toastr.success(
                        //     data.message,
                        //     '',
                        //     {
                        //         timeOut: 500,
                        //         fadeOut: 500,
                        //         onHidden: function () {
                        //             window.location.reload()
                        //         }
                        //     }
                        // )
                        Swal.fire(
                            'information',
                            data.message,
                            'success'
                        ).then(function () {
                            window.location.reload()
                        })
                    }
                    else {
                        Swal.fire({
                            icon: 'error',
                            tittle: 'warning',
                            text: data.message,
                        })
                    }
                }
            })
        }
    })
</script>

med_id/med_id/Views/MMedicalItem/Detail.cshtml
@using med_id.viewmodels;


@model VMMMedicalItem

@{
    ViewData["Title"] = "Create Medical Item";
}

<div class="card">
    <div class="card-body">

        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>


        <div class="mb-4 row">
            <label for="Name" class="col-sm-4 col-form-label">Name</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" readonly>
                <span id="validate_Name" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-4 row">
            <label for="MedicalItemCategoryId" class="col-sm-4 col-form-label">Price Min</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="MedicalItemCategoryId" name="MedicalItemCategoryId" value="@Model.NameCategory" readonly>
            </div>
        </div>
        <div class="mb-4 row">
            <label for="MedicalItemSegmentationId" class="col-sm-4 col-form-label">Price Min</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="MedicalItemSegmentationId" name="MedicalItemSegmentationId" value="@Model.NameSegmentation" readonly>
            </div>
        </div>

        <div class="mb-4 row">
            <label for="PriceMin" class="col-sm-4 col-form-label">Price Min</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="PriceMin" name="PriceMin" value="@Model.PriceMin" readonly>
            </div>
        </div>
        <div class="mb-4 row">
            <label for="PriceMax" class="col-sm-4 col-form-label">Price Max</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="PriceMax" name="PriceMax" value="@Model.PriceMax" readonly>
            </div>
        </div>

        <div class="mb-4 row">
            <label for="Packaging" class="col-sm-4 col-form-label">packaging</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Packaging" name="Packaging" value="@Model.Packaging" readonly>
            </div>
        </div>

        <div class="mb-4 row">
            <label for="Indication" class="col-sm-4 col-form-label">Indication</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Indication" name="Indication" value="@Model.Indication" readonly />
            </div>
        </div>

        <div class="mb-4 row">
            <label for="Caution" class="col-sm-4 col-form-label">Jenis Obat</label>
            <div class="col-sm-8">
                <input type="radio" name="Caution" value="bebas" checked disabled> Obat Bebas (Tanpa Resep) <br><br>
                <input type="radio" name="Caution" value="keras" disabled> Obat Keras <br><br>
            </div>
        </div>


        <div class="mb-4 row">
            <label for="ImageFile" class="col-sm-4 col-form-label">Image</label>
            <div class="col-sm-8">
                @if (Model.ImagePath != null)
                {
                    <img src="~/images/@Model.ImagePath" class="img-thumbnail" height="200" width="200"></img>
                    <br />
                    <br />
                    <input type:"text" style="text-align:center; border:0px" id="ImageFile" name="ImageFile" value="@Model.ImagePath.Split('_',2)[1]" readonly>
                }
            </div>
        </div>


        <div class="mb-4 row">
            <div class="col-sm-8">
                <a class="btn btn-light" asp-controller="MMedicalItem" asp-action="Index">Back to List</a>
            </div>
        </div>

    </div>
</div>

med_id/med_id/Views/MMedicalItem/Edit.cshtml
@using med_id.viewmodels;


@model VMMMedicalItem

@{
    ViewData["Title"] = "Create Medical Item";
}

<div class="card">
    <div class="card-body">

        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>

        <form asp-action="Edit" method="post" id="form_input" enctype="multipart/form-data">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">


            <div class="mb-4 row">
                <label for="Name" class="col-sm-4 col-form-label">Name</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
                    <span id="validate_Name" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="MedicalItemCategoryId" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @if (ViewBag.ListCategory != null)
                    {
                        @Html.DropDownList("MedicalItemCategoryId",
                    new SelectList(ViewBag.ListCategory, "Id", "Name"),
                    "--Pilih Category--",
                    new {@class = "form-control"}
                    )
                    }
                    else
                    {
                        <p>Error: Data for dropdown is null.</p>
                    }
                </div>
            </div>

            <div class="mb-4 row">
                <label for="MedicalItemSegmentationId" class="col-sm-4 col-form-label">Name Segmentation</label>
                <div class="col-sm-8">
                    @if (ViewBag.ListVariant != null)
                    {
                        @Html.DropDownList("MedicalItemSegmentationId",
                    new SelectList(ViewBag.ListVariant, "Id", "Name"),
                    "--Pilih Variant--",
                    new {@class = "form-control"}
                    )
                    }
                    else
                    {
                        <p>Error: Data for dropdown is null.</p>
                    }
                </div>
            </div>

            <div class="mb-4 row">
                <label for="PriceMin" class="col-sm-4 col-form-label">Price Min</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="PriceMin" name="PriceMin" value="@Model.PriceMin">
                </div>
            </div>
            <div class="mb-4 row">
                <label for="PriceMax" class="col-sm-4 col-form-label">Price Max</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="PriceMax" name="PriceMax" value="@Model.PriceMax">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Packaging" class="col-sm-4 col-form-label">packaging</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Packaging" name="Packaging" value="@Model.Packaging">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Indication" class="col-sm-4 col-form-label">Indication</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Indication" name="Indication" value="@Model.Indication" />
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Caution" class="col-sm-4 col-form-label">Jenis Obat</label>
                <div class="col-sm-8">
                    <input type="radio" name="Caution" value="bebas" checked> Obat Bebas (Tanpa Resep) <br><br>
                    <input type="radio" name="Caution" value="keras"> Obat Keras <br><br>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="ImageFile" class="col-sm-4 col-form-label">Upload Image</label>
                <div class="col-sm-8">
                    <input type="file" class="form-control" id="ImageFile" name="ImageFile" value="@Model.ImagePath">
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="MMedicalItem" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            },
            PriceMin: {
                required: true,
                number: true,
            },
            PriceMax: {
                required: true,
                number: true,
            },
            Packaging: {
                required: true,
            },
            Indication: {
                required: true,
            },
            MedicalItemCategoryId: "required",
            MedicalItemSegmentationId: "required",
            ImageFile: {
                required: true,
                typeFile: "jpg|jpeg|png",
                sizeFile: true,
            },
        },
        messages: {
            Name: {
                required: "Please fill Name",
                minlength: "The name must consist of at least 3 character"
            },
            PriceMin: {
                required: "Please fill price",
                number: "Please fill number only",
            },
            PriceMax: {
                required: "Please fill price",
                number: "Please fill number only",
            },
            Packaging: {
                required: "Please fill Packaging",
                number: "Please fill number only",
            },
            Indication: {
                required: "Please fill Packaging",
                number: "Please fill number only",
            },
            MedicalItemCategoryId: "Please select category",
            MedicalItemSegmentationId: "Please select category",
            ImageFile: {
                required: "Please fill image",
                typeFile: "Please upload jpg|jpeg|png",
                sizeFile: "Please upload file max size 1 mb",
            },
        },
        submitHandler: function (form) {
            var name = $("#Name").val()
            var id = $("#Id").val()
            var medicalItemSegmentationId = $("#MedicalItemSegmentationId").val()
            var medicalItemCategoryId = $("#MedicalItemCategoryId").val()

            $.ajax({
                url: "/MMedicalItem/CheckNameIsExist",
                type: "get", //type atau method sama aja.
                data: { name: name, id: id, medicalItemSegmentationId: medicalItemSegmentationId, medicalItemCategoryId: medicalItemCategoryId },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_Name").text("Name is Already Exists");
                        return true;
                    }
                    else {
                        fungsiSubmit(form)
                    }
                }

            })
        }
    })

    function fungsiSubmit(form) {
        var formData = new FormData()
        var dataForm = $(form).serializeArray()
        $.each(dataForm, function (key, input) {
            formData.append(input.name, input.value)
        })
        var file = $("#ImageFile").prop("files")
        if (file.length > 0) {
            formData.append("ImageFile", file[0])
        }
        $.ajax({
            url: "/MMedicalItem/Edit",
            type: "post",
            data: formData,
            dataType: "json",
            contentType: false,
            processData: false,
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")

                    Swal.fire(
                        'information',
                        data.message,
                        'success'
                    ).then(function () {
                        window.location.reload()
                    })


                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }
    jQuery.validator.addMethod("typeFile", function (value, element, param) {
        return value.match(new RegExp("." + param + "$"));
    });
    jQuery.validator.addMethod("sizeFile", function (val, element) {
        var size = element.files[0].size;
        if (size > 1048576)// checks the file more than 1 MB
        {
            return false;
        } else {
            return true;
        }
    });

</script>