med_id/med_id/Controllers/AuthController.cs
using med_id.Services;
using med_id.viewmodels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Protocol;

namespace med_id.Controllers
{
    public class AuthController : Controller
    {
        private AuthService authService;
        VMResponse response = new VMResponse();
        public AuthController(AuthService _authService)
        {
            authService = _authService;
        }
        public IActionResult Login()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> Login(string email, string password)
        {
            VMResponse responseLogin = await authService.CheckLogin(email, password);
            Console.WriteLine("response login = " + responseLogin.Entity.ToJson());
            if (!responseLogin.Success)
            {
                response.Success = false;
                response.Message = responseLogin.Message;
                return Json(response);
            }

            VMBiodataUser user = JsonConvert.DeserializeObject<VMBiodataUser>(responseLogin.Entity.ToString());

            HttpContext.Session.SetInt32("IdUser", (int)user.Id);
            HttpContext.Session.SetInt32("IdRole", (int)user.RoleId);
            HttpContext.Session.SetInt32("IdBiodata", (int)user.BiodataId);
            HttpContext.Session.SetString("FullName", user.NameUser);
            HttpContext.Session.SetString("NameRole", user.NameRole);
            

            response.Message = responseLogin.Message;

            return Json(response);
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

med_id/med_id/Controllers/DoctorController.cs
using med_id.datamodels;
using med_id.Services;
using med_id.viewmodels;
using Microsoft.AspNetCore.Mvc;

namespace med_id.Controllers
{
    public class DoctorController : Controller
    {
        private DoctorService doctorService;
        private SpesialisasiDokterService spesialisasiDokterService;


        private readonly IWebHostEnvironment webHostEnvirontment;
        public DoctorController(DoctorService _dokterService, IWebHostEnvironment _webHostEnvirontment, SpesialisasiDokterService _spesialisasiDokterService)
        {
            doctorService = _dokterService;
            webHostEnvirontment = _webHostEnvirontment;
            spesialisasiDokterService = _spesialisasiDokterService;
        }
        public async Task<IActionResult> IndexDetail(int id)
        {
            VMDoctorProfile data = await doctorService.GetDataByIdProfile(id);
            return View(data);
        }
        public async Task<IActionResult> Index(int id)
        {
            VMDoctorProfile data = await doctorService.GetDataByIdProfile(id);
            return View(data);
        }
        public string Upload(IFormFile ImageFile)
        {
            string uniqueFileName = "";

            if (ImageFile != null)
            {
                string uploadFolder = Path.Combine(webHostEnvirontment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    ImageFile.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        [HttpPost]
        public async Task<IActionResult> SaveImg(VMSavePoto dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.ImagePath = Upload(dataParam.ImageFile);
            }
            //dataParam.CreateBy = IdUser;
            VMResponse respon = await doctorService.SaveImg(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Create(int id)
        {
            VMDoctorProfile data = await doctorService.GetDataByIdProfile(id);

            List<MSpecialization> listCategory = await spesialisasiDokterService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMDoctorProfile dataParam)
        {
            dataParam.CreatedBy = 1;
            VMResponse respon = await doctorService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMDoctorProfile data = await doctorService.GetDataByIdProfile(id);

            List<MSpecialization> listCategory = await spesialisasiDokterService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMDoctorProfile dataParam)
        {
            dataParam.CreatedBy = 1;
            VMResponse respon = await doctorService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<JsonResult> CheckTokenIsExist(int id, string nameDay, int nameJam, int nameMenit)
        {
            string day = nameDay;
            if (day == "1")
            {
                day = "Senin";
            }
            if (day == "2")
            {
                day = "Selasa";
            }
            if (day == "3")
            {
                day = "Rabu";
            }
            if (day == "4")
            {
                day = "Kamis";
            }
            if (day == "5")
            {
                day = "Jumat";
            }
            if (day == "6")
            {
                day = "Sabtu";
            }
            if (day == "0")
            {
                day = "Minggu";
            }
            bool isExist = await doctorService.CheckJadwal(id, day, nameJam, nameMenit);
            return Json(isExist);
        }

    }
}

med_id/med_id/Views/Shared/_Header.cshtml
@using med_id.Services;
@inject DoctorService doctorService;
@{
    int IdRole = Context.Session.GetInt32("IdRole") ?? 5;
    string Name = Context.Session.GetString("FullName") ?? "";
    string NameRole = Context.Session.GetString("NameRole") ?? "";
    int idBio = Context.Session.GetInt32("IdBiodata") ?? 0;
    int doc =0;
    if (IdRole == 2)
    {
        var doctor = await doctorService.GetDataDoctor(idBio);
        doc = Convert.ToInt32(doctor.Id);
    }
}

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="index.html" class="logo d-flex align-items-center">
            <i class="ri-hospital-line ri-3x" style="color: darkblue"></i>
            <span class="d-none d-lg-block">MedId</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->
            @if (IdRole == 5)
            {
                <li class="nav-item p-4">
                    <a id="btn_login" class="d-flex align-items-center btn" style="cursor:pointer; background-color:darkblue; color: white;">
                        <i class="bi bi-box-arrow-in-right"></i>
                        <span>Login</span>
                    </a>
                </li>
            }
            else
            {
                <li class="nav-item dropdown">

                    <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                        <i class="bi bi-bell"></i>
                        <span class="badge bg-primary badge-number">4</span>
                    </a><!-- End Notification Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                        <li class="dropdown-header">
                            You have 4 new notifications
                            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-exclamation-circle text-warning"></i>
                            <div>
                                <h4>Lorem Ipsum</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>30 min. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-x-circle text-danger"></i>
                            <div>
                                <h4>Atque rerum nesciunt</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>1 hr. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-check-circle text-success"></i>
                            <div>
                                <h4>Sit rerum fuga</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>2 hrs. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="notification-item">
                            <i class="bi bi-info-circle text-primary"></i>
                            <div>
                                <h4>Dicta reprehenderit</h4>
                                <p>Quae dolorem earum veritatis oditseno</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class="dropdown-footer">
                            <a href="#">Show all notifications</a>
                        </li>

                    </ul><!-- End Notification Dropdown Items -->

                </li>

                <!-- End Notification Nav -->

                <li class="nav-item dropdown">

                    <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                        <i class="bi bi-chat-left-text"></i>
                        <span class="badge bg-success badge-number">3</span>
                    </a><!-- End Messages Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                        <li class="dropdown-header">
                            You have 3 new messages
                            <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="message-item">
                            <a href="#">
                                <img src="~/niceadmin/img/messages-1.jpg" alt="" class="rounded-circle">
                                <div>
                                    <h4>Maria Hudson</h4>
                                    <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                    <p>4 hrs. ago</p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="message-item">
                            <a href="#">
                                <img src="~/niceadmin/img/messages-2.jpg" alt="" class="rounded-circle">
                                <div>
                                    <h4>Anna Nelson</h4>
                                    <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                    <p>6 hrs. ago</p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="message-item">
                            <a href="#">
                                <img src="~/niceadmin/img/messages-3.jpg" alt="" class="rounded-circle">
                                <div>
                                    <h4>David Muldon</h4>
                                    <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                    <p>8 hrs. ago</p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li class="dropdown-footer">
                            <a href="#">Show all messages</a>
                        </li>

                    </ul><!-- End Messages Dropdown Items -->

                </li>

                <!-- End Messages Nav -->

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="~/niceadmin/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@Name</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>@Name</h6>
                            <span>@NameRole</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" asp-controller="Doctor" asp-action="Index" asp-route-id="@doc">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                                <i class="bi bi-gear"></i>
                                <span>Account Settings</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                                <i class="bi bi-question-circle"></i>
                                <span>Need Help?</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a asp-controller="Auth" asp-action="Logout" class="dropdown-item d-flex align-items-center">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li> <!-- End Profile Nav -->
            }

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

<script>
    $("#btn_login").click(function () {
        $("#modal-body").empty()
        $("#modal-body").load("/Auth/Login")
        $("#my_modal").modal("show")
    })
</script>

med_id/med_id/Views/Shared/_Layout.cshtml
@{
    int idRole = @Context.Session.GetInt32("IdRole") ?? 5;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <!-- Sweet Alert -->
    <script src="~/SweetAlert/sweetalert2/sweetalert2.js"></script>

    <!-- Toastr -->
    <script src="~/toastr/toastr.min.js"></script>
    
    <!-- Favicons -->
    <link href="~/niceadmin/img/favicon.png" rel="icon">
    <link href="~/niceadmin/img/apple-touch-icon.png" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/niceadmin/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/niceadmin/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/niceadmin/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/niceadmin/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/niceadmin/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/niceadmin/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/niceadmin/vendor/simple-datatables/style.css" rel="stylesheet">
     
    <!-- Datepicker -->
    <link href="~/bootstrap-datepicker/css/bootstrap-datepicker3.css" rel="stylesheet" />
    <script src="~/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>


    <!-- Template Main CSS File -->
    <link href="~/niceadmin/css/style.css" rel="stylesheet">
    <link href="~/niceadmin/css/custom-style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: NiceAdmin
    * Updated: Nov 17 2023 with Bootstrap v5.3.2
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
    <div class="main-layout">
        <input type="hidden" id="get-id" value="@idRole" />

        <partial name="_Header" />

        <partial name="_Sidebar" />

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


        <footer class="border-top footer text-muted" hidden>
            <div class="container">
                &copy; 2023 - med_id
            </div>
        </footer>
    </div>

    
    <div class="modal fade" id="my_modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal-body">
                    Non omnis incidunt qui sed occaecati magni asperiores est mollitia. Soluta at et reprehenderit. Placeat autem numquam et fuga numquam. Tempora in facere consequatur sit dolor ipsum. Consequatur nemo amet incidunt est facilis. Dolorem neque recusandae quo sit molestias sint dignissimos.
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" id="modal_check_slot">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center" id="modal_load_body">
                    <div class="spinner-border text-primary" role="status">
                    </div>
                    <h3>Cek Ketersediaan Jadwal</h3>
                    <p>Mohon menunggu, kami sedang mengecek ketersediaan waktu konsultasi.</p>
                </div>
            </div>
        </div>
    </div>

    <!--Spinners-->
    <div class="modal fade" id="modal_load">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center" id="modal_load_body">
                    <div class="spinner-grow text-primary" role="status">
                        <span class="sr-only"></span>
                    </div>
                    <h3 id="title_load"></h3>
                </div>
            </div>
        </div>
    </div>

    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@

    <!-- Vendor JS Files -->
  <script src="~/niceadmin/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/niceadmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/niceadmin/vendor/chart.js/chart.umd.js"></script>
  <script src="~/niceadmin/vendor/echarts/echarts.min.js"></script>
  <script src="~/niceadmin/vendor/quill/quill.min.js"></script>
  <script src="~/niceadmin/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/niceadmin/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/niceadmin/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
    <script src="~/niceadmin/js/main.js"></script>

    <script>
        var id = $("#get-id").val()
        if(id != 5){
            $(".main-layout").addClass("container-main")
        }
    </script>

    @* @await RenderSectionAsync("Scripts", required: false) *@
</body>
</html>

med_id/med_id/Views/Shared/_Sidebar.cshtml
@using med_id.Services
@inject AuthService authService;

@{
    int IdUser = @Context.Session.GetInt32("IdUser") ?? 5;
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 5;
    string RoleName = Context.Session.GetString("NameRole") ?? "";
    var menu = await authService.MenuAccess(IdRole);
}

@if(IdRole != 5)
{
    <aside id="sidebar" class="sidebar">
        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-item">
                <a class="nav-link " asp-controller="Home" asp-action="Index">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>

        @{
            foreach(var parent in menu)
            {
                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#components-nav-@parent.Id" data-bs-toggle="collapse" href="#" aria-expanded="false">
                        <i class="bi bi-menu-button-wide"></i><span>@parent.Name</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    
                    <ul id="components-nav-@parent.Id" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        @foreach(var child in parent.listChild)
                        {
                            <li>
                                <a href="@child.Url" aria-expanded="false">
                                    <i class="@child.SmallIcon" style="font-size:25px"></i><span>@child.Name</span>
                                </a>
                            </li>
                        }
                    </ul>
                </li>
            }
        }
        </ul>
    </aside>
}